package app.utils.iterable

operator fun <E> List<E>.component6(): E = this[5]
operator fun <E> List<E>.component7(): E = this[6]
operator fun <E> List<E>.component8(): E = this[7]
operator fun <E> List<E>.component9(): E = this[8]
operator fun <E> List<E>.component10(): E = this[9]
operator fun <E> List<E>.component11(): E = this[10]
operator fun <E> List<E>.component12(): E = this[11]
operator fun <E> List<E>.component13(): E = this[12]
operator fun <E> List<E>.component14(): E = this[13]
operator fun <E> List<E>.component15(): E = this[14]
operator fun <E> List<E>.component16(): E = this[15]
operator fun <E> List<E>.component17(): E = this[16]
operator fun <E> List<E>.component18(): E = this[17]
operator fun <E> List<E>.component19(): E = this[18]
operator fun <E> List<E>.component20(): E = this[19]
operator fun <E> List<E>.component21(): E = this[20]
operator fun <E> List<E>.component22(): E = this[21]
operator fun <E> List<E>.component23(): E = this[22]
operator fun <E> List<E>.component24(): E = this[23]
operator fun <E> List<E>.component25(): E = this[24]
operator fun <E> List<E>.component26(): E = this[25]
operator fun <E> List<E>.component27(): E = this[26]
